### PR TITLE
Update architecture.adoc

### PR DESCRIPTION
**Pull request by MarciaRieferJohnston**
- Swapped in a `<<pointer to the figure>>` instead of " As shown in Figure 1" since this figure isn't always #1.
- Made the footnote smaller type.
- Made the architecture diagram dimensions 100% x 100% instead of specific height and width.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by annaone — APPROVED** [review]

**Comment by MarciaRieferJohnston** [comment]
> Architecture diagrams don't always get generated at a specific height and width.

That's exactly why the current line of code jumped out at me. Right now, we specify "width=648,height=439" for the diagram.

**Review by andrew-glenn — APPROVED** [review]

**Comment by andrew-glenn** [comment]
This got merged into the wrong branch. @MarciaRieferJohnston , I may need you to re-open this PR against the `main` branch.

**Comment by MarciaRieferJohnston** [comment]
@andrew-glenn Per our conversation just now, we'll let this PR sit until PR #62 is sorted. Then, if all goes well, this PR may merge into `main` just fine.

**Comment by andrew-glenn** [comment]
reverted in #76

**Pull request merged**
