### PR TITLE
Changed team name (Quick Start > I&A) in byline

### PR DESCRIPTION
**Pull request by MarciaRieferJohnston**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by andrew-glenn** [comment]
Converted to draft for now pending internal discussiosn

**Review by andrew-glenn — CHANGES_REQUESTED** [review]
blanket _request changes_ to ensure we have a stop-gap while we investigate our ducks being in a row

**Comment by andrew-glenn** [comment]
Upon further review, I didn't get the memo. Clearly this has the appropriate cover sheet. Approving.

**Review by andrew-glenn — APPROVED** [review]

**Review by dowen12 — APPROVED** [review]
New names

**Pull request merged**
