### PR TITLE
Removed "paid"

### PR DESCRIPTION
**Pull request by MarciaRieferJohnston**
The word "paid" adds no value since we're already talking about costs.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by annaone** [comment]
@MarciaRieferJohnston - that phrase was given to us by Tad to add to our deployment guides. I would leave it there.

**Review by annaone — COMMENTED** [review]
Tad gave us this phrase to add to our guides. I would leave it as is.

**Review by DelfinGala — APPROVED** [review]

**Comment by MarciaRieferJohnston** [comment]
@annaone I get your point. Tad asked us to add the phrase about the third-party licenses. Daniel suggested today that we remove the word "paid," and I agree. This edit removes redundancy from the sentence while leaving Tad's meaning intact.

**Review by andrew-glenn — CHANGES_REQUESTED** [review]
Words matter. Deferring to Tad as he's the source of this language. Happy to unblock after reaffirming

**Review by annaone — APPROVED** [review]

**Comment by MarciaRieferJohnston** [comment]
@andrew-glenn Tad just confirmed in Slack that this phrasing (without "paid") is fine. Please unblock.

**Review by andrew-glenn — APPROVED** [review]

**Pull request merged**
